server:
  port: 5080

spring:
  application:
    name: wendi.agents
  datasource:
    username: 'postgres'
    password: 'sema' #'skylite=2011'
    #Local:: jdbc:postgresql://localhost:5432/agents_db jdbc:postgresql://wendi_agents:5432/agents_db --for docker
    url: jdbc:postgresql://localhost:5432/agents_db
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: true
    hibernate:
      ddl-auto: update